---
- name: Add "{{ ansible_user }}" user to libvirt group and get ssh key setup
  user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: yes
    state: present
    generate_ssh_key: yes
  become: yes
  tags: user
