---
- name: Configure firewalld
  block:
    - name: Enable HTTP for firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      become: yes

    - name: Open port {{ webserver_caching_port }}/tcp, zone public, for cache for firewalld
      firewalld:
        port: "{{ webserver_caching_port }}/tcp"
        permanent: yes
        state: enabled
        zone: "public"
        immediate: yes
      become: yes
      when: cache_enabled|bool
  when: firewall != "iptables"
  tags: firewall

- name: Configure iptables
  block:
    - name: Enable HTTP for iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "80"
        jump: ACCEPT
      become: yes

    - name: Open port {{ webserver_caching_port }}/tcp for cache for iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ webserver_caching_port }}"
        jump: ACCEPT
      become: yes
      when: cache_enabled|bool

    - name: Allow related and established connections for iptables
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      become: yes

    - name: Save iptables configuration
      shell: |
        /usr/sbin/iptables-save > /etc/sysconfig/iptables
      become: yes
  when: firewall == "iptables"
  tags: firewall
