[id="ansible-playbook-checklist"]

= Fully Disconnected Prerequiste Checklist

* [ ] NIC1 VLAN is configured on the provisioning network.
* [ ] NIC2 VLAN is configured on the  baremetal network.
* [ ] NIC1 is PXE-enabled on the provisioning network for the control plane (master) and worker nodes.
* [ ] (Optional) NIC2 is PXE-enabled on *only* the provisioning node for easy deployment of RHEL operating system via a local Satellite server or PXE server
* [ ] Aside from provisioning network NIC1, PXE has been disabled on all other NICs for all {product-title} nodes
* [ ] DNS records configured for the {product-title} nodes using a subdomain or subzone and cluster name i.e. `<cluster-name>.<domain-name>`
* [ ] DHCP reservations for the {product-title} nodes, API, ingress endpoint, and nameserver.
* [ ] A separate out-of-band management network has been created.
* [ ] All nodes accessible via out-of-band management network.
* [ ] Required data for installation (out-of-band management IP and credentials, provisioning NIC1 MAC address for all {product-title} nodes.
* [ ] Ensure `release.txt` file exists within the webserver path/to/webserver/<ocp_release_version>
* [ ] Ensure `rhcos.json` file exists within the webserver path/to/webserver/<ocp_release_version>
* [ ] Ensure `openshift-baremetal-install` binary exists within the webserver path/to/webserver/<ocp_release_version>
* [ ] Ensure `release.txt` file exists within the webserver path/to/webserver/<ocp_release_version>
* [ ] Ensure `openshift-client-linux-<ocp_release_version>.tar.gz` tar.gz exists within the webserver path/to/webserver/<ocp_release_version>
* [ ] Create `registry-auths.json`
* [ ] Create `install-config-appends.json`
