[id="ansible-playbook-tour-of-the-ansible-playbook"]

= Tour of the Ansible Playbook

* `inventory` - contains the file `hosts.sample` that:
** contains all the modifiable variables, their default values, and their definition. Some variables are empty ensuring users give an explicit value.
** the setting up of your provision node, master nodes, and worker nodes. Each section will require additional details (i.e. Management credentials).
* `requirements` - contains the list of collections required by the playbook.
** The collections include two roles: `redhatci.ocp.node_prep` and `redhatci.ocp.installer`. `redhatci.ocp.node_prep` handles all the prerequisites that the provisioner node requires prior to running the installer. The `redhatci.ocp.installer` role handles extracting the installer, setting up the manifests, and running the Red Hat OpenShift installation.

The tree structure is shown below:

[source,bash]
----
├── ansible.cfg
├── inventory
│   └── hosts.sample
├── playbook.yml
└── requirements.yml
----
