[id="ansible-playbook-contents-of-the-webserver"]

= Contents of the Webserver
//FIXME This link doesn't exist yet, bc piece is not a module
When following the details on how to create a link:Deployment#ipi-install-creating-an%20rhcos-images-cache_ipi-install-prerequisites[webserver], if one not already in place, there is still additional content required for
a fully disconnected environment to be successfully deployed with the Ansible playbook.

The Ansible playbook requires the end user to additionally include the following
to there already existing webserver.

The example provided below showcases how a user adds the required prerequisites
to the webserver in order install the latest
{product-title} version {product-version}.

.Automatic Procedure
. Change to the webserver directory that is to store your OpenShift related binaries
+
[source,bash]
----
[user@webserver ~]$ cd /path/to/webserver/dir
----
+
. Create a local copy of <<env_vars, environment variables script>> and make the script executable.
+
[source,bash]
----
[user@webserver ~]$ chmod +x /path/to/webserver/dir/env_vars.sh
----
+
. Create a local copy of <<helper_script, helper script>> that downloads all the prerequisites to the webserver
+
[source,bash]
----
[user@webserver ~]$ chmod +x /path/to/webserver/dir/helper_script.sh
----
+
. Open the the `env_vars.sh` script and fill out the appopriate environment variable values
+
. Run the `helper_script.sh` script
+
[source,bash]
----
[user@webserver ~]$ /path/to/webserver/dir/helper_script.sh
----
+
[NOTE]
====
Using the `helper_script.sh` has some caveats. Extracting the
`openshift-baremetal-install` binary does not pull from a local registry when
given a local registry, https://bugzilla.redhat.com/show_bug.cgi?id=1823143[BZ#1823143]
Due to this, in order to properly extract the installer, the OpenShift disconnected
mirrored registry that is to be used must be available and have access to quay.io
temporary to properly extract the binary.
====

NOTE: The following manual procedure can be skipped if used the <<helper_script, helper script>>.

.Manual Procedure
//FIXME This link doesn't exist bc ocp4.5 isn't GA, should we just point to 4.4 as an example? Do we want to provide the dev link too?
. Download the {product-title} version {product-version} latest https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-{product-version}/release.txt[release.txt] file
+
[source,bash]
[subs="attributes"]
----
[user@webserver ~]$ cd /path/to/webserver/dir
[user@webserver ~]$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-{product-version}/release.txt
----
+
[NOTE]
====
When working with a development version of {product-title}, use the following link for the
development version of the
https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-{product-version}/release.txt[release.txt]
====
+
. Create a directory with the explict release version of the captured release.txt file
+
[source,bash]
----
export OCP_RELEASE=`cat release.txt | grep Name | awk {'print $2'}`
[user@webserver ~]$ mkdir $OCP_RELEASE
----
+

. Move the release.txt file to the newly created release version directory
+
[source,bash]
----
[user@webserver ~]$ mv release.txt $OCP_RELEASE/
----
+

. Download the `oc` client and untar its contents
+
[source,bash]
----
[user@webserver ~]$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_RELEASE/openshift-client-linux-$OCP_RELEASE.tar.gz | tar zxvf - oc
----
+

. Extract the Installer
+
[NOTE]
====
Extracting the installer currently has some caveats. Extracting the
`openshift-baremetal-install` binary does not pull from a local registry when
given a local registry, https://bugzilla.redhat.com/show_bug.cgi?id=1823143[BZ#1823143]
Due to this, in order to properly extract the installer, the OpenShift disconnected
mirrored registry that is to be used must be available and have access to quay.io
temporary to properly extract the binary. The following step assumes this.
====
+
[source,bash]
----
[user@webserver ~]$ export LOCAL_REPOSITORY='ocp4'
[user@webserver ~]$ export LOCAL_REGISTRY='registry.example.com:5000'
[user@webserver ~]$ export cmd=openshift-baremetal-install
[user@webserver ~]$ export pullsecret_file=~/pull-secret.txt
[user@webserver ~]$ export extract_dir=$(pwd)
[user@webserver ~]$ oc adm release extract --registry-config "${pullsecret_file}" --command="${cmd}" --to `pwd` ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}
----
+

. Ensure the `openshift-baremetal-install` binary points to the appopriate release image (i.e. `registry.example.com` )
+
[source,bash]
----
[user@webserver ~]$ ./openshift-baremetal-install version
openshift-baremetal-install 4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image registry.example.com:5000/ocp4/openshift4@sha256:e805d6a36762e22ecf66fd3f3642e609a00ed25ab44f89f064b5138cf3f0f554
----
+

. The `rhcos.json` file is required for the disconnected installs as it contains
the appropriate image name and SHA hash
+
NOTE: This assumes the `openshift-baremetal-install` has been extracted

+
[source,bash]
----
[user@webserver ~]$ export COMMIT_ID=$(./openshift-baremetal-install version | grep '^built from commit' | awk '{print $4}')
[user@webserver ~]$ curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json > rhcos.json
----
+

. Clean up the `oc` and `kubelet` binary extraction as no longer required
+

[source,bash]
----
[user@webserver ~]$ rm -f /path/to/$OCP_RELEASE/oc /path/to/$OCP_RELEASE/kubelet
----

. Confirm all four files have been captured within your $OCP_RELEASE directory
+
[source,bash]
----
[user@webserver ~]$ ls -latr /path/to/$OCP_RELEASE
openshift-baremetal-install openshift-client-linux-$OCP_RELEASE.tar.gz rhcos.json release.txt
----
