language: ruby
cache:
  bundler: true
rvm:
- 2.3.3
before_install:
- bundle install
script:
- rake

after_success:
- touch website/_site/.nojekyll

deploy:
  skip_cleanup: true
  provider: pages
  token: "$GITHUB_TOKEN"
  keep_history: false
  target_branch: gh-pages
  local_dir: website/_site/
  on:
    branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    secure: mAJIvVS39g4pQF8lqVqGgdsV0n1/qhbUelvDl0rMk8V15E+CSp+9ED/n1IZKEZ5aA81Bw5HnVstqxU/I5ZHdYabM7pfE8bQnmvDY8buRN+C5ckc/tER6bopxM8sUGnN4AISuTmH9w1WhFxMPkNMTUVSEY4OREf4mHeKda+UQTa4NL3dWJcg9kGSnyXdJzbuX/PjvDBiBkglfT61EEh+xqsz80K3ewsAoBntXT7hNeWwzA0sPRn0YMstj/LWkStYLZVzRk4KcDzUjyunwFSQg1LkGcJcaPFIiuwvL8rL7eATndMnIivDMvoBJAyJ7UGUNCAbXutRe5pEE/YQh5nOnYwkGKb63I3bFskHhltQYzuwr83Ng1HBnYS/M97JyTkAApMiPLzmmK7K+oyXIZUUH6LZBn612gHvcRR46iZVup3DVOOePR3fIFiA5YVFbuZtrtHB0QzDOLndEzSuDsroBSnEwgzncbs0dTWEIT1ll5PDXM0ObWRA3Z/jdIL3m9v8y+wpGSjDsDaxYWNmdHfPPhWcdB4eYXzpha7KvZUUK1ndC6Jl/2I79u6lYdymVrwfymJeAEhLTfy+oq8yWToU0Mh7ygZ8HRKTmZ91YnfYxIeBbFAIOnbDMS+vgnkMEoAHyOVW1coAJgMqjW+VSEHZH71vvDMCOKQomlfMGhOC2QC4=

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
