apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
    labels:
        machineconfiguration.openshift.io/role: worker-rt
    name: 11-rt-kernel-worker-rt
spec:
    kernelArguments:
        - 'non_iso_cpumask=00000005'
    config:
        ignition:
            config: {}
            security:
                tls: {}
            timeouts: {}
            version: 2.2.0
        networkd: {}
        passwd: {}
        storage:
            files:
                - filesystem: root
                  path: /usr/local/bin/pre-boot-tuning.sh
                  mode: 0700
                  contents:
                      source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCnNldCAtZXVvIHBpcGVmYWlsCgojIFRPRE86IGltcHJvdmUgY2hlY2sgZm9yIGFwcGxpZWQgY29uZmlndXJhdGlvbgppZiBncmVwIC1xICJDUFVBZmZpbml0eSIgIi9ldGMvc3lzdGVtZC9zeXN0ZW0uY29uZiI7IHRoZW4KICAgIGVjaG8gIlByZSBib290IHR1bmluZyBjb25maWd1cmF0aW9uIGFscmVhZHkgYXBwbGllZCIKZWxzZQogICAgZWNobyAiW01hbmFnZXJdIiA+PiAvZXRjL3N5c3RlbWQvc3lzdGVtLmNvbmYKICAgIGVjaG8gIkNQVUFmZmluaXR5PTAgMiIgPj4gL2V0Yy9zeXN0ZW1kL3N5c3RlbS5jb25mCiAgICBlY2hvICJJUlFCQUxBTkNFX0JBTk5FRF9DUFVTPUZGRkZGRkZBIiA+PiAvZXRjL3N5c2NvbmZpZy9pcnFiYWxhbmNlCgogICAgcnBtLW9zdHJlZSBpbml0cmFtZnMgLS1lbmFibGUgLS1hcmc9LUkgLS1hcmc9L2V0Yy9zeXN0ZW1kL3N5c3RlbS5jb25mCiAgICBycG0tb3N0cmVlIGluaXRyYW1mcyAtLWVuYWJsZSAtLWFyZz0tSSAtLWFyZz0vZXRjL3N5c2NvbmZpZy9pcnFiYWxhbmNlCiAgICAKICAgIHN5c3RlbWN0bCByZWJvb3QKZmkKCg==
        systemd:
            units:
                - contents: |
                      [Unit]
                      Description=Pre boot kernel tuning
                      Wants=rt-kernel.service
                      After=rt-kernel.service
                      Before=kubelet.service

                      [Service]
                      Type=exec
                      RemainAfterExit=true

                      ExecStart=/usr/local/bin/pre-boot-tuning.sh

                      [Install]
                      WantedBy=multi-user.target
                  enabled: true
                  name: pre-boot-tuning.service