---

- name: Copy PullSecret into {{ pullsecret_file }}
  copy:
    content: "{{ pullsecret }}"
    dest: "{{ pullsecret_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: 
  - pullsecret
  - extract

- name: Extracting the installer
  shell: |
    /usr/local/bin/oc adm release extract --registry-config {{ pullsecret_file | quote }} --command={{ cmd |quote }} --to {{ tempdir | quote }} {{ release_image | quote }}
  args:
    chdir: "{{ tempdir }}"
    executable: /bin/bash
  tags: extract

- name: Copy openshift-baremetal-install binary to /usr/local/bin
  copy:
    src: "{{ tempdir }}/openshift-baremetal-install"
    dest: /usr/local/bin/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    remote_src: yes
  become: yes
  tags: extract
