---
- name: Add Kubeconfig to Ansible User .bashrc
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export KUBECONFIG={{ dir }}/auth/kubeconfig"

- name: Deploy OpenShift Cluster
  shell: |
    /usr/local/bin/openshift-baremetal-install --dir {{ dir }} --log-level debug create cluster

