galaxy_info:
  author: Roger Lopez
  description: The bridge-setup role sets up the required bridges on the provision host.
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
