[id="ipi-install-troubleshooting-ntp-out-of-sync"]
[[ntp]]
= NTP out of sync

The deployment of OpenShift clusters depends on having synced time.
Without synced time, the deployment may fail due to the time
inaccuracies if larger than two seconds. For
example, notice the AGE of the nodes below.

[source,bash]
----
[kni@provisioner ~]$ oc get nodes
NAME                         STATUS   ROLES    AGE   VERSION
master-0.cloud.example.com   Ready    master   145m   v1.16.2
master-1.cloud.example.com   Ready    master   135m   v1.16.2
master-2.cloud.example.com   Ready    master   145m   v1.16.2
worker-2.cloud.example.com   Ready    worker   100m  v1.16.2
----

This leads to inconsistent timing delays as shown below

[source,bash]
----
[kni@provisioner ~]$ oc get bmh -n openshift-machine-api
master-1   error    registering              kni7-master-1         ipmi://<out-of-band-ip>

#sudo timedatectl
               Local time: Tue 2020-03-10 18:20:02 UTC
           Universal time: Tue 2020-03-10 18:20:02 UTC
                 RTC time: Tue 2020-03-10 18:36:53
                Time zone: UTC (UTC, +0000)
System clock synchronized: no
              NTP service: active
          RTC in local TZ: no
----

In an already existing cluster, this can be
fixed by following the below steps.

- Add `+chrony.conf+` file and encode it as `base64`, for example:

[source,bash]
----
cat << EOF | base 64
server <NTP-server> iburst
stratumweight 0
driftfile /var/lib/chrony/drift
rtcsync
makestep 10 3
bindcmdaddress 127.0.0.1
bindcmdaddress ::1
keyfile /etc/chrony.keys
commandkey 1
generatecommandkey
noclientlog
logchange 0.5
logdir /var/log/chrony
EOF
[text-in-base-64]
----

- Create the `+MachineConfig+` file, replacing the `base64` string with
the one you just created yourself. This example adds the file to master
nodes. You can change it to worker or make an additional
`+MachineConfig+` for the worker role:

[source,yaml]
----
[kni@provisioner ~]$ cat << EOF > ./99_masters-chrony-configuration.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-etc-chrony-conf
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,[text-in-base-64]
          verification: {}
        filesystem: root
        group:
          name: root
        mode: 420
        path: /etc/chrony.conf
        user:
          name: root
    systemd: {}
  osImageURL: ""
----

Make a backup copy of the configuration file.

Since, the cluster is already running, apply the file as follows:

[source,bash]
----
[kni@provisioner ~]$ oc apply -f ./masters-chrony-configuration.yaml
sudo timedatectl
               Local time: Tue 2020-03-10 19:10:02 UTC
           Universal time: Tue 2020-03-10 19:10:02 UTC
                 RTC time: Tue 2020-03-10 19:36:53
                Time zone: UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
----

NOTE: When wanting to setup time sync prior to deployment,
generate manifest files, add this file to
the `openshift` directory, then continue to create the cluster.

[source,bash]
----
[kni@provisioner ~]$ cp chrony-masters.yaml <Install-Dir>/ocp/openshift/99_masters-chrony-configuration.yaml
----
