apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-realtime-node
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Optimize systems running OpenShift realtime nodes
      include=openshift-node-network-latency

      [selinux]
      avc_cache_threshold=8192

      [net]
      nf_conntrack_hashsize=131072

      [sysctl]
      kernel.hung_task_timeout_secs = 600
      kernel.nmi_watchdog = 0
      kernel.sched_rt_runtime_us = -1
      vm.stat_interval = 10
      kernel.timer_migration = 0
      #vm.nr_hugepages=${hugepage_num}

      #[sysfs]
      #/sys/bus/workqueue/devices/writeback/cpumask = ${not_isolated_cpumask}
      #/sys/devices/virtual/workqueue/cpumask = ${not_isolated_cpumask}
      #/sys/devices/system/machinecheck/machinecheck*/ignore_ce = 1

      [scheduler]
      isolated_cores=${isolated_cores}
    name: openshift-realtime-node
  recommend:
  - priority: 30
    profile: openshift-realtime-node
    match:
    - label: node-role.kubernetes.io/worker-rt
