// Module included in the following assemblies:
//
// * installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

[id='node-requirements_{context}']
= Node requirements

IPI installation involves a number of hardware node requirements:

- **CPU architecture:** All nodes *must* use `x86_64` CPU architecture.

ifeval::[{release} > 4.3]
- **Unified Extensible Firmware Interface (UEFI):** UEFI boot is required on all {product-title} nodes when using IPv6 addressing on the `provisioning` network. In addition, UEFI Device PXE Settings must be set to use the IPv6 protocol on the `provisioning` network NIC.
endif::[]

- **Similar nodes:** Nodes *should* have an identical configuration per role. That is, control plane nodes *should* be the same brand and model with the same CPU, RAM and storage configuration. Worker nodes should be *identical*.

//<IS CPU PINNING/NUMA AN ISSUE???>

- **Intelligent Platform Management Interface (IPMI):** IPI installation requires IPMI enabled on each node.

- **Latest generation:** Nodes should be of the most recent generation. IPI installation relies on IPMI, which should be compatible across nodes. Additionally, RHEL 8 ships with the most recent drivers for RAID controllers. Ensure that the nodes are recent enough to https://catalog.redhat.com/hardware/servers/search?p=1&c_version=Red%20Hat%20Enterprise%20Linux%208&ch_architecture=x86_64[support RHEL 8] for the provisioning node and all the {product-title} nodes.

- **Network interfaces:** Each node *must* have at least two network interfaces (NICs)- one for the `provisioning` network and one for the public `baremetal` network.
Network interface names *must* follow the same naming convention across all nodes.
For example, the first NIC name on a node, such as `eth0` or `eno1`, should be the same name on all of the other nodes.
The same principle applies to the remaining NICs on each node. It is recommended these network interfaces be 10 GB NICs.

- **Provisioning node:** IPI installation requires one provisioning node.

- **Control plane:** IPI installation requires three control plane (master) nodes for high availability.

- **Worker nodes (Optional):** A typical production cluster may include worker nodes. IPI installation in a high availability environment provides the flexibility of deploying an initial cluster with or without worker nodes. If worker nodes are deployed, at *least* two worker nodes are required for the initial cluster deployment.
//IS ZERO WORKERS SUPPORTED IN 4.3?

- **Registry node:** (Optional) If setting up a disconnected mirrored registry, it is recommended this reside in its own node.
