
[id='ipi-install-firmware-requirements-for-installing-with-virtual-media_{context}']

= Firmware requirements for installing with virtual media

The installer for installer-provisioned {product-title} clusters validates the hardware and firmware compatibility with RedFish virtual media. The following table lists supported firmware for installer-provisioned {product-title} clusters deployed with RedFish virtual media.

.Firmware Compatibility for RedFish Virtual Media
[frame="topbot", options="header"]
|====
|Hardware| Model | Management | Minimum Firmware Version
.2+| HP | 10th Generation | iLO5 | v1.9
| 9th Generation | iLO4 | v1.8

.2+| Dell | 14th Generation | iDRAC 9 | v4.20.20.20+

| 13th Generation .2+| iDRAC 8 | v2.75.75.75+

|====

[NOTE]
====
Refer to your hardware documentation or contact your vendor for information on updating your firmware.
====


[IMPORTANT]
====
The installer will not initiate installation on a node if the node firmware is below the foregoing versions when installing with virtual media.
====
