// Module included in the following assemblies:
//
// * list of assemblies where this module is included
// ipi-install-installation-workflow.adoc
// Upstream module

[id="deploying-the-provisioner-node-as-a-worker-node-using-metal3_{context}"]

= Deploying the provisioner node as a worker node using Metal3

After you have completed the prerequisites, perform the deployment process.

.Procedure

. Power off the node using `ipmitool` and confirm the provisioning node is powered off.
+
[source,bash]
----
ssh <server-with-access-to-management-net>
# Use the user, password and Management net IP adddress to shutdown the system
ipmitool -I lanplus -U <user> -P <password> -H <management-server-ip> power off
# Confirm the server is powered down
ipmitool -I lanplus -U <user> -P <password> -H <management-server-ip> power status
Chassis Power is off
----

. Get `base64` strings for the Out of band Management credentials. In this example, the user is `root` and the password is `calvin`.
+
[source,bash]
----
# Use echo -ne, otherwise you will get your secrets with \n which will cause issues
# Get root username in base64
echo -ne "root" | base64
# Get root password in base64
echo -ne "calvin" | base64
----

. Configure the BaremetalHost `bmh.yaml` file.
+
[source,yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker-2-bmc-secret
type: Opaque
data:
  username: ca2vdAo=
  password: MWAwTWdtdC0K
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-worker-2
spec:
  online: true
  bootMACAddress: <NIC1-mac-address>
  bmc:
    address: ipmi://<out-of-band-ip>
    credentialsName: openshift-worker-2-bmc-secret
----

. Create the BaremetalHost.
+
[source,bash]
----
./oc -n openshift-machine-api create -f bmh.yaml
secret/openshift-worker-2-bmc-secret created
baremetalhost.metal3.io/openshift-worker-2 created
----

. Power up and inspect the node.
+
[source,bash]
----
./oc -n openshift-machine-api get bmh openshift-worker-2

NAME                 STATUS   PROVISIONING STATUS   CONSUMER   BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-2   OK       inspecting                       ipmi://<out-of-band-ip>                      true
----

. After finishing the inspection, the node is ready to be provisioned.
+
[source,bash]
----
./oc -n openshift-machine-api get bmh openshift-worker-2

NAME                 STATUS   PROVISIONING STATUS   CONSUMER   BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-2   OK       ready                            ipmi://<out-of-band-ip>   unknown            true
----

. Scale the workers machineset. Previously, there were two replicas during original installation.
+
[source,bash]
----
./oc get machineset -n openshift-machine-api
NAME            DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-worker-2   0         0                             21h

./oc -n openshift-machine-api scale machineset openshift-worker-2 --replicas=3
----

. The baremetal host moves to provisioning status. This can take as long as 30 minutes. You can follow the status
from the node console.
+
[source,bash]
----
oc -n openshift-machine-api get bmh openshift-worker-2

NAME                 STATUS   PROVISIONING STATUS   CONSUMER                  BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-2   OK       provisioning          openshift-worker-0-65tjz   ipmi://<out-of-band-ip>   unknown            true
----

. When the node is provisioned it moves to provisioned status.
+
[source,bash]
----
oc -n openshift-machine-api get bmh openshift-worker-2

NAME                 STATUS   PROVISIONING STATUS   CONSUMER                  BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-2   OK       provisioned           openshift-worker-2-65tjz   ipmi://<out-of-band-ip>   unknown            true
----

. When the `kubelet` finishes initialization the node is ready for use.
You can connect to the node and run `journalctl -fu kubelet` to check the process.
+
[source,bash]
----
oc get node
NAME                                            STATUS   ROLES           AGE     VERSION
openshift-master-0.openshift.example.com        Ready    master          30h     v1.16.2
openshift-master-1.openshift.example.com        Ready    master          30h     v1.16.2
openshift-master-2.openshift.example.com        Ready    master          30h     v1.16.2
openshift-worker-0.openshift.example.com        Ready    worker          3m27s   v1.16.2
openshift-worker-1.openshift.example.com        Ready    worker          3m27s   v1.16.2
openshift-worker-2.openshift.example.com        Ready    worker          3m27s   v1.16.2
----
