
//
// * list of assemblies where this module is included
// ipi-install-prerequisites.adoc
// Upstream module

[id="creating-dhcp-reservations-using-dnsmasq-option2_{context}"]

= Configuring dnsmasq (Option 2)

Set up `dnsmasq` on a server that can access the baremetal network.

.Procedure

. Install `dnsmasq`.
+
[source,bash]
----
dnf install -y dnsmasq
----

. Change to the `/etc/dnsmasq.d` directory.
+
[source,bash]
----
cd /etc/dnsmasq.d
----

. Create a file that reflects your OpenShift cluster appended by `.dns`.
+
[source,bash]
----
touch <filename>.dns
----

. Open the appropriate `firewalld` DHCP service.
+
[source,bash]
----
systemctl restart firewalld
firewall-cmd --add-service=dhcp --permanent
firewall-cmd --reload
----

. Define DNS configuration file

+
[discrete]
=== IPv4
+
Here is an example of the `.dns` file for IPv4.
+
----
domain-needed
bind-dynamic
bogus-priv
domain=openshift.example.com
dhcp-range=<baremetal-net-starting-ip,baremetal-net-ending-ip>
#dhcp-range=10.0.1.4,10.0.14
dhcp-option=3,<baremetal-net-gateway-ip>
#dhcp-option=3,10.0.1.254
resolv-file=/etc/resolv.conf.upstream
interface=<nic-with-access-to-baremetal-net>
#interface=em2
server=<ip-of-existing-server-on-baremetal-net>


#Wildcard for apps -- make changes to cluster-name (openshift) and domain (example.com)
address=/.apps.openshift.example.com/<wildcard-ingress-lb-ip>

#Static IPs for Masters
dhcp-host=<NIC2-mac-address>,provisioner.openshift.example.com,<ip-of-provisioner>
dhcp-host=<NIC2-mac-address>,openshift-master-0.openshift.example.com,<ip-of-openshift-master-0>
dhcp-host=<NIC2-mac-address>,openshift-master-1.openshift.example.com,<ip-of-openshift-master-1>
dhcp-host=<NIC2-mac-address>,openshift-master-2.openshift.example.com,<ip-of-openshift-master-2>
dhcp-host=<NIC2-mac-address>,openshift-worker-0.openshift.example.com,<ip-of-openshift-worker-0>
dhcp-host=<NIC2-mac-address>,openshift-worker-1.openshift.example.com,<ip-of-openshift-worker-1>
----

ifdef::upstream[]
ifeval::[{release} >= 4.5]
+
[discrete]
=== IPv6
+
Here is an example of the `.dns` file for IPv6.
+
----

strict-order
bind-dynamic
bogus-priv
dhcp-authoritative
dhcp-range=baremetal,<baremetal-IPv6-dhcp-range-start>,<baremetal-IPv6-dhcp-range-end>,<range-prefix>
dhcp-option=baremetal,option6:dns-server,[<IPv6-DNS-Server>]

resolv-file=/etc/resolv.conf.upstream
except-interface=lo
dhcp-lease-max=81
log-dhcp

domain=openshift.example.com,<baremetal-IPv6-cidr>,local

# static host-records
address=/apps.openshift.example.com/<wildcard-ingress-lb-ip>
host-record=api.openshift.example.com,<api-ip>
host-record=ns1.openshift.example.com,<dns-ip>
host-record=openshift-master-0.openshift.example.com,<ip-of-openshift-master-0>
host-record=openshift-master-1.openshift.example.com,<ip-of-openshift-master-1>
host-record=openshift-master-2.openshift.example.com,<ip-of-openshift-master-1>
# Registry
host-record=registry.openshift.example.com,<ip-of-registry-server>

#Static IPs for Masters
dhcp-host=<baremetal-nic-duid>,openshift-master-0.openshift.example.com,<ip-of-openshift-master-0>
dhcp-host=<baremetal-nic-duid>,openshift-master-1.openshift.example.com,<ip-of-openshift-master-1>
dhcp-host=<baremetal-nic-duid>,openshift-master-2.openshift.example.com,<ip-of-openshift-master-2>
----
endif::[]
endif::[]


. Create the `resolv.conf.upstream` file to provide DNS fowarding to an existing DNS server for resolution
to the outside world.
+
----
search <domain.com>
nameserver <ip-of-my-existing-dns-nameserver>
----

. Restart the `dnsmasq` service.
+
[source,bash]
----
systemctl restart dnsmasq
----

. Verify the `dnsmasq` service is running.
+
[source,bash]
----
systemctl status dnsmasq
----
