// Module included in the following assemblies:
//
// * list of assemblies where this module is included
// ipi-install-installation-workflow.adoc
// Upstream module

[id="adding-a-worker-node-to-an-existing-cluster_{context}"]

= Adding a worker node to an existing cluster

.Procedure

. Retrieve the username and password of the bare metal node's baseboard management controller. Then, create `base64` strings from the username and password. In the following example, the username is `root` and the password is `calvin`.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ echo -ne "root" | base64
----
+
[source,bash]
----
[kni@openshift-master-0 ~]$ echo -ne "calvin" | base64
----


. Create a configuration file for the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ vim bmn.yaml
----
+
[source,yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker-<num>-bmc-secret
type: Opaque
data:
  username: <base64-of-uid>
  password: <base64-of-pwd>
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-worker-<num>
spec:
  online: true
  bootMACAddress: <NIC1-mac-address>
  bmc:
    address: ipmi://<bmc-ip>
    credentialsName: openshift-worker-<num>-bmc-secret
----
+
Replace `<num>` for the worker number of bare metal node in two `name` fields and `credentialsName` field. Replace `<base64-of-uid>` with the `base64` string of the username. Replace `<base64-of-pwd>` with the `base64` string of the password. Replace `<NIC1-mac-address>` with the MAC address of the bare metal node's first NIC. Replace `<bmc-ip>` with the IP address of the bare metal node's baseboard management controller.

[NOTE]
====
When using `redfish` or `redfish-virtualmedia`, add the
appropriate addressing as described in the BMC addressing section. See xref:ipi-install-bmc-addressing_{context}[BMS addressing] for details.
====

. Create the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api create -f bmn.yaml
----
+
[source,bash]
----
secret/openshift-worker-<num>-bmc-secret created
baremetalhost.metal3.io/openshift-worker-<num> created
----
+
Where `<num>` will be the worker number.

. Power up and inspect the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api get bmn openshift-worker-<num>
----
+
Where `<num>` is the worker node number.
+
[source,bash]
----
NAME                 STATUS   PROVISIONING STATUS   CONSUMER   BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-<num>   OK       ready                            ipmi://<out-of-band-ip>   unknown            true
----

. Ensure the `PROVISIONING STATUS` is `ready` before provisioning the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$  oc -n openshift-machine-api get bmn openshift-worker-<num>
----
+
Where `<num>` is the worker node number.
+
[source,bash]
----
NAME                 STATUS   PROVISIONING STATUS   CONSUMER   BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-<num>   OK       ready                            ipmi://<out-of-band-ip>   unknown            true
----

. Get a count of the number of worker nodes.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc get nodes
----

. Get the machine set.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc get machinesets -n openshift-machine-api
----

. Increase the number of worker nodes by 1.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc scale --replicas=<num> machineset <machineset> -n openshift-machine-api
----
+
Replace `<num>` with the new number of worker nodes. Replace `<machineset>` with the name of the machine set from the previous step.

. Check the status of the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api get bmh openshift-worker-<num>
----
+
Where `<num>` is the worker node number. The status changes from `ready` to `provisioning`.
+
[source,bash]
----
NAME                 STATUS   PROVISIONING STATUS   CONSUMER                  BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-<num>   OK       provisioning          openshift-worker-<num>-65tjz   ipmi://<out-of-band-ip>   unknown            true
----
+
The `provisioning` status remains until the {product-title} cluster provisions the node. This may take 30 minutes or more. Once complete, the status will change to `provisioned`.
+
[source,bash]
----
NAME                 STATUS   PROVISIONING STATUS   CONSUMER                  BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-<num>   OK       provisioned           openshift-worker-<num>-65tjz   ipmi://<out-of-band-ip>   unknown            true
----

. Once provisioned, ensure the bare metal node is ready.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc get nodes
----
+
[source,bash]
----
NAME                                                STATUS   ROLES           AGE     VERSION
openshift-master-0.openshift.example.com            Ready    master          30h     v1.16.2
openshift-master-1.openshift.example.com            Ready    master          30h     v1.16.2
openshift-master-2.openshift.example.com            Ready    master          30h     v1.16.2
openshift-worker-<num>.openshift.example.com        Ready    worker          3m27s   v1.16.2
----
+
You can also check the kubelet.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ ssh openshift-worker-<num>
----
+
[source,bash]
----
[kni@openshift-worker-<num>]$ journalctl -fu kubelet
----
