// This is included in the following assemblies:
//
// installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
[id='bmc-addressing-for-fujitsu_{context}']

= BMC addressing for Fujitsu

The `address` field for each `bmc` entry is a URL for connecting to the {product-title} cluster nodes, including the type of controller in the URL scheme and its location on the network.

[source,yaml]
----
platform:
  baremetal:
    hosts:
      - name: <host name>
        role: <master | worker>
        bmc:
          address: <address>
          username: <user>
          password: <password>
----

For Fujitsu hardware, Red Hat supports iRMC and IPMI.

.BMC address formats for Fujitsu hardware
[frame="topbot",options="header"]
|====
|Protocol|Address Format
|iRMC| `irmc://<out-of-band-ip>`
|IPMI| `ipmi://<out-of-band-ip>`
|====

See the following sections for additional details.

.iRMC for Fujitsu

Fujitsu nodes can use `irmc://<out-of-band-ip>` and defaults to port `623`. The following example demonstrates an iRMC configuration within the `install-config.yaml` file.

[source,yaml]
----
platform:
  baremetal:
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: irmc://<out-of-band-ip>
          username: <user>
          password: <password>
----

.IPMI

Hosts using IPMI use the `ipmi://<out-of-band-ip>:<port>` address format, which defaults to port `623` if not specified. The following example demonstrates an IPMI configuration within the `install-config.yaml` file.

[source,yaml]
----
platform:
  baremetal:
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://<out-of-band-ip>
          username: <user>
          password: <password>
----

[NOTE]
====
IPMI does not encrypt communications. It is suitable for use within a data center over a secured network.
====
