
//
// * installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

[id="configuring-the-install-config-file_{context}"]

= Configuring the `install-config.yaml` file

The `install-config.yaml` file requires some additional details.
Most of the information is teaching the installer and the resulting cluster enough about the available hardware so that it is able to fully manage it.

. Configure `install-config.yaml`. Change the appropriate variables to match the environment, including `pullSecret` and `sshKey`.
+
[source,yaml, subs="verbatim,macros"]
----
ifeval::[{release} > 4.5]
include::ipi-install-config-yaml.adoc[]
endif::[]
ifeval::[{release} == 4.5]
include::ipi-install-config-yaml-4.5.adoc[]
endif::[]
ifeval::[{release} == 4.4]
include::ipi-install-config-yaml-4.4.adoc[]
endif::[]
ifeval::[{release} <= 4.3]
include::ipi-install-config-yaml-4.3.adoc[]
endif::[]
----

ifdef::upstream[]
+
<1> Refer to the xref:bmcaddressing[BMC adressing] for more options
endif::[]

. Create a directory to store cluster configs.
+
[source,terminal]
----
[kni@provisioner ~]$ mkdir ~/clusterconfigs
[kni@provisioner ~]$ cp install-config.yaml ~/clusterconfigs
----

. Ensure all bare metal nodes are powered off prior to installing the {product-title} cluster.
+
[source,terminal]
----
[kni@provisioner ~]$ ipmitool -I lanplus -U <user> -P <password> -H <management-server-ip> power off
----

. Remove old bootstrap resources if any are left over from a previous deployment attempt.
+
[source,terminal]
----
for i in $(sudo virsh list | tail -n +3 | grep bootstrap | awk {'print $2'});
do
  sudo virsh destroy $i;
  sudo virsh undefine $i;
  sudo virsh vol-delete $i --pool default;
  sudo virsh vol-delete $i.ign --pool default;
done
----
