// This is included in the following assemblies:
//
// ipi-install-expanding-the-cluster.adoc

[id='preparing-the-bare-metal-node_{context}']

= Preparing the bare metal node

Preparing the bare metal node requires executing the following procedure from a control plane node.

.Procedure

. Get the `oc` binary.
+
----
[kni@openshift-master-0 ~]$ curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/$VERSION/openshift-client-linux.tar.gz | tar zxvf - oc
[kni@openshift-master-0 ~]$ sudo cp oc /usr/local/bin
----

. Install the `ipmitool`.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ sudo dnf install -y OpenIPMI ipmitool
----

. Power off the bare metal node and ensure it is off.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ ipmitool -I lanplus -U <user> -P <password> -H <management-server-ip> power off
----
+
Where `<management-server-ip>` is the IP address of the bare metal node's base board management controller.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ ipmitool -I lanplus -U <user> -P <password> -H <management-server-ip> power status
----
+
[source,bash]
----
Chassis Power is off
----

. Retrieve the username and password of the bare metal node's baseboard management controller. Then, create `base64` strings from the username and password. In the following example, the username is `root` and the password is `calvin`.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ echo -ne "root" | base64
----
+
[source,bash]
----
[kni@openshift-master-0 ~]$ echo -ne "calvin" | base64
----

. Create a configuration file for the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ vim bmn.yaml
----
+
[source,yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker-<num>-bmc-secret
type: Opaque
data:
  username: <base64-of-uid>
  password: <base64-of-pwd>
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-worker-<num>
spec:
  online: true
  bootMACAddress: <NIC1-mac-address>
  bmc:
    address: ipmi://<bmc-ip>
    credentialsName: openshift-worker-<num>-bmc-secret
----
+
Replace `<num>` for the worker number of bare metal node in two `name` fields and `credentialsName` field. Replace `<base64-of-uid>` with the `base64` string of the username. Replace `<base64-of-pwd>` with the `base64` string of the password. Replace `<NIC1-mac-address>` with the MAC address of the bare metal node's first NIC. Replace `<bmc-ip>` with the IP address of the bare metal node's baseboard management controller.

. Create the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api create -f bmn.yaml
----
+
[source,bash]
----
secret/openshift-worker-<num>-bmc-secret created
baremetalhost.metal3.io/openshift-worker-<num> created
----
+
Where `<num>` will be the worker number.

. Power up and inspect the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api get bmn openshift-worker-<num>
----
+
Where `<num>` is the worker node number.
+
[source,bash]
----
NAME                 STATUS   PROVISIONING STATUS   CONSUMER   BMC                 HARDWARE PROFILE   ONLINE   ERROR
openshift-worker-<num>   OK       ready                            ipmi://<out-of-band-ip>   unknown            true
----

. Check the status of the bare metal node.
+
[source,bash]
----
[kni@openshift-master-0 ~]$ oc -n openshift-machine-api get bmh openshift-worker-<num>
----
+
Where `<num>` is the worker node number. The status should change to `ready`.
