// Module included in the following assemblies:
//
// * installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

[id="additional-install-config-parameters_{context}"]
= Additional `install-config` parameters

This topic describes the required parameters, the `hosts` parameter, 
and the `bmc` `address` parameter for the `install-config.yaml` file.

.Required parameters

|===
|Parameters |Default |Description
| `provisioningNetworkInterface` |  | The name of the network interface on control plane nodes connected to the
provisioning network. ({product-title} 4.4 only)
| `hosts` |  | Details about bare metal hosts to use to build the cluster.
| `defaultMachinePlatform` | | The default configuration used for machine pools without a platform configuration.
| `apiVIP` | `api.<clusterdomain>` | The VIP to use for internal API communication.

This setting must either be provided or pre-configured in DNS so that the
default name resolve correctly.
| `ingressVIP` | `test.apps.<clusterdomain>` | The VIP to use for ingress traffic.

ifeval::[{release} < 4.5]
This setting must either be provided or pre-configured in DNS so that the
default name resolve correctly.
|`dnsVIP` | | The VIP to use for internal DNS communication.

This setting has no default and must always be provided.
endif::[]
|===

.Hosts

The `hosts` parameter is a list of separate bare metal assets that 
should be used to build the cluster.

|===
|Name |Default |Description
| `name` |  | The name of the `BareMetalHost` resource to associate with the details.
| `role` |  | Either `master` or `worker`.
| `bmc` | | Connection details for the baseboard management controller. See below for details.
| `bootMACAddress` |  | The MAC address of the NIC the host will use to boot on the provisioning network.
|===

The `bmc` parameter for each host is a set of values for accessing the 
baseboard management controller in the host.

|===
|Name |Default |Description
| `username` |  | The username for authenticating to the BMC.
| `password` |  | The password associated with `username`.
| `address` | | The URL for communicating with the BMC controller, based on the provider being used.
See BMC Addressing for details.
|===

== BMC addressing

The `address` field for each `bmc` entry is a URL with details how to 
connect to the {product-title} cluster nodes, including the type of 
controller in the URL scheme and its location on the network.

.IPMI

IPMI hosts use `ipmi://<out-of-band-ip>:<port>` and defaults to port 
`623` if not specified. Example output of using IPMI within your 
`install-config.yaml` file.

----
platform:
  baremetal:
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://<out-of-band-ip>
          username: <user>
          password: <password>
----

ifeval::[{release} > 4.4]

.RedFish

For RedFish, use `redfish://` (or `redfish+http://` to disable TLS). 
The hostname (or IP address) and the path to the system ID are both 
required. Example output of using RedFish within your 
`install-config.yaml` file.

----
platform:
  baremetal:
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: redfish://<out-of-band-ip>/redfish/v1/Systems/1
          username: <user>
          password: <password>
----

While it is recommended to have a certificate of authority for your 
out of band management addresses, if using self-signed certificates 
ensure to include an additional parameter of 
`disableCertificateVerification: True`. Example output of using
RedFish with `disableCertificateVerification: True` 
within your `install-config.yaml` file.

----
platform:                                                               
  baremetal:                                                            
    hosts:                                                              
      - name: openshift-master-0                                        
        role: master                                                    
        bmc:                                                            
          address: redfish://<out-of-band-ip>/redfish/v1/Systems/1      
          username: <user>                                              
          password: <password> 
          disableCertificateVerification: True 
----

NOTE: Currently RedFish is only supported on HPE hardware for IPI on 
Bare metal deployments. We are working with other vendors to enable 
RedFish capabilities across the board. 

.RedFish Virtual Media

For RedFish virtual media, use `redfish-virtualmedia://`

Example output of using RedFish Virtual Media 
within your `install-config.yaml` file.                         

----
platform:                                                               
  baremetal:                                                            
    hosts:                                                              
      - name: openshift-master-0                                        
        role: master                                                    
        bmc:                                                            
          address: redfish-virtualmedia://<out-of-band-ip>/redfish/v1/Systems/1      
          username: <user>                                              
          password: <password>                                          
----

NOTE: Currently RedFish is only supported on HPE hardware for IPI on 
Bare metal deployments. We are working with other vendors to enable 
RedFish capabilities across the board. 

endif::[]
