---
- name: Register host via Activation key
  redhat_subscription:
    activationkey: "{{ activation_key }}"
    org_id: "{{ org_id }}"
    state: present
    pool: '^(Red Hat Enterprise Linux Server, Standard (8 sockets) (Unlimited guests))$'
    force_register: true
  ignore_errors: true
  become: true
  when:
    - activation_key != ""
    - org_id != ""
  tags: subscription
