---
- name: Enable and restart Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: true
  with_items:
    - libvirtd
  tags: services

- name: Enable Services (iptables)
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: true
  with_items:
    - "{{ firewall }}"
  tags: services
  when: firewall == "iptables"

- name: Enable Services (firewalld)
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  with_items:
    - "{{ firewall }}"
  tags: services
  when: firewall != "iptables"
