apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ${sriovnetworkname}
  namespace: ${operatornamespace}
spec:
  ipam: |
    {
      "type": "dhcp"
    }
  networkNamespace: ${targetnamespace}
  resourceName: ${sriovresourcename}
  vlan: ${vlan}
