#!/usr/bin/env bash

PERFORMANCE_DIR="$(
    cd "$(dirname "$BASH_SOURCE[0]")/../"
    echo "$(pwd)"
)"

ASSETS_DIR="${PERFORMANCE_DIR}/assets"
MANIFESTS_DIR="${PERFORMANCE_DIR}/manifests"
TEMPLATES_DIR="${MANIFESTS_DIR}/templates"
MANIFESTS_GENERATED_DIR="${MANIFESTS_GENERATED_DIR:-$MANIFESTS_DIR/generated}"

ISOLATED_CPUS=${ISOLATED_CPUS:-}
RESERVED_CPUS=${RESERVED_CPUS:-}
