Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source "https://rubygems.org"

gem "jekyll"
gem "rake"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "html-proofer"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "premonition", "~> 2.0.1"
gem "jekyll-tagging"
gem "jekyll-theme-minimal"
gem "github-pages", group: :jekyll_plugins
